#!/bin/bash
############################################################################
# Copyright (C) 2014 Allwinnertech Incorporated                            #
#                                                                          #
# Foundation, Inc.,                                                        #
#                                                                          #
############################################################################
# File: do_tigerreplay.sh                                                  #
#                                                                          #
# Description:  This script can be used to the tests                       #
#                                                                          #
# Authors:      zhengjinyong - zhengjinyong@allwinnertech.com              #
#                                                                          #
# History:      Jan 03 2014 - Created - zhengjinyong                       #
#               - main functions                                           #
#               - clean up on script exit                                  #
############################################################################

usage() 
{
  cat <<-EOF >&2

  usage: ${0##*/} [ -f tiger_script ] [ -c loop_count ] [ -l logdir]
              
  -f tiger_script  The lhs script to replay is generated by TigerRobot.
  -c loop_count    loop count. 
  -l logdir        The path where logfile to store.

	EOF
exit 0
}

function check_device() {
   adb remount || \
   {
       echo "device remount failed!"
       exit;
   }
}

function do_tigerreplay() {
    begin=$(date +%s)
    
    tiger_script=$1
    loop_count=$2
    LOG_NAME=${tiger_script%.lhs}"_logcat.txt"
    KMSG_LOGNAME=${tiger_script%.lhs}"_kmsg.txt"

    adb push tigerreplay /system/bin/ || \
    {
        echo "push tigereplay failed!"
        return 1;
    }

    adb push $tiger_script /mnt/sdcard/ || \
    {
        echo "push $tiger_script failed!"
        return 1;
    }

    adb shell chmod 755 /system/bin/tigerreplay
    adb shell "rm /mnt/sdcard/$LOG_NAME"
    adb shell "logcat -c" 
    adb shell "logcat -v time -f /mnt/sdcard/$LOG_NAME" &

    adb shell "rm /mnt/sdcard/$KMSG_LOGNAME"

    adb shell dmesg -c 1>/dev/null 2>&1
    adb shell "cat /proc/kmsg > /mnt/sdcard/$KMSG_LOGNAME" &
    
    LCD_BL=`adb shell cat /sys/class/disp/disp/attr/lcd_bl | tr -d '\n\r'`
    if [ "$LCD_BL" = "0" ]; then
        adb shell input keyevent 26
    fi
    
    for ((i = 1; i <= $2; i++))
    do
        echo "第$i次循环"
        adb shell tigerreplay /mnt/sdcard/${TIGER_SCRIPT} || \
        {
            echo "tigerreplay error" 
            return 2
        }
    done

    end=$(date +%s)
    spend=$(expr $end - $begin)  
    echo "测试时间: $spend秒"   
    
    exit_handle
}

function exit_handle() {
    adb pull /mnt/sdcard/${LOG_NAME} ${LOGDIR}
    adb pull /mnt/sdcard/${KMSG_LOGNAME} ${LOGDIR}
    kill %1
    kill %2
}

function main() {
    
    TIGER_SCRIPT=""
    LOOP_COUNT=3
    LOGDIR=`pwd`
    
    while getopts f:c:l: arg
    do  case $arg in
        f)  TIGER_SCRIPT=$OPTARG;;

        c)  LOOP_COUNT=$OPTARG;;

        l)  LOGDIR=$OPTARG;;

        \?) usage;;
        esac
    done

    [ -z $TIGER_SCRIPT ] && \
    {
        echo "must have -f parameter" 
        usage
    }

    check_device
    do_tigerreplay $TIGER_SCRIPT $LOOP_COUNT
}

trap "exit_handle" INT 
main "$@"
