
all:
	gcc 4_stack.c stack_darr/stack.c -I./stack_darr/
w5:
	gcc 5_stack.c stack_darr/stack.c -I./stack_darr/
w6:
	gcc 6_stack.c stack_darr/stack.c -I./stack_darr/
w7:
	gcc 7_stack.c stack_darr/stack.c -I./stack_darr/

w8:
	gcc d_queue.c b_queue_llist/queue.c -I./b_queue_llist	

